iturmas/views/pages.py
import os

from flask import Blueprint, render_template, session, redirect, jsonify, url_for, flash, request
from werkzeug.security import generate_password_hash
import markdown as md

import config
from iturmas.decorators import login_required
from iturmas.api import auth
from driver.control import peek, CLEAN, RUNNING, SUCCESS, FAILURE, ZOMBIE, get_progress
from driver.extract import get_courses_and_classes_data, get_parameters
from iturmas.decorators.auth import clear_session
from models import Student, Course, Turma, CourseApplication, User

bp = Blueprint('pages', __name__)


@bp.route('/reset_password/<token>')
def reset_password(token):
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('pages.login', messages=['O link para definição de senha não é válido.']))
    return render_template('reset_password.html', token=token)


@bp.route('/define_new_password')
def define_new_password():
    return render_template('define_new_password.html')


@bp.route('/request_define_password')
def request_define_password():
    response, code = auth.request_define_password()
    if code == 400:
        flash('O email não está registrado em nossas bases de dados.')
    else:
        flash('Você receberá um e-mail em instantes com instruções para definir nova senha.')
    return render_template('login.html')


@bp.route('/set_password', methods=['POST'])
def set_password():
    try:
        token = request.form['reset_password_token']
        password1 = request.form['password1']
        password2 = request.form['password2']
        assert password1 == password2
    except KeyError:
        # This should not happen if user "used" served form
        return redirect(url_for('pages.login'))

    user = User.verify_reset_password_token(token)
    if not user:
        # TODO: check this actually goes to the login page...
        flash('O link para definição de senha não é válido.')
        return redirect(url_for('pages.login'))

    user.password = generate_password_hash(password1, salt_length=16)
    user.save(on_duplicate_key_update=True)

    # TODO: check this actually goes to the login page...
    flash('Nova senha definida com sucesso! Tente fazer login.')
    return redirect(url_for('pages.login'))


@bp.route('/<domain>/index')
@login_required(roles='admin', api_route=False)
def generic_index(domain):
    if domain not in ['classes', 'courses', 'students']:
        return jsonify({'error': 'Invalid domain.'}), 400
    return render_template(domain + '.html')


@bp.route('/')
@login_required(api_route=False)
def index():
    print(session.session_object.role)
    if session.session_object.role == 'admin':
        return redirect('/panel')
    return redirect('/pref/main')


@bp.route('/login')
def login():
    return render_template('login.html')


@bp.route('/help')
def app_help():
    try:
        with open('../README.md') as f:
            html = md.markdown(f.read())
    except IOError:
        flash('Help não foi encontrado, por favor contacte o administrador.')
        return redirect(url_for('pages.index'))

    return render_template('help.html', html_content=html)


@bp.route('/logout')
def logout():
    clear_session()
    return redirect(url_for('pages.login', next=''))


# noinspection PyBroadException
@bp.route('/panel')
@login_required(roles='admin', api_route=False)
def panel():
    try:
        _1, _2, criteria_list = get_courses_and_classes_data()
    except:
        criteria_list = ['Error in driver: could not fetch list of criteria.']
    return render_template(
        'panel.html',
        default_max_search=config.DEFAULT_MAX_SEARCH,
        parameters=get_parameters(criteria_list)
    )


@bp.route('/list_stats')
@login_required(roles='admin', api_route=False)
def list_stats():
    data = {
        'users': User.count(),
        'students': Student.count(),
        'courses': Course.count(),
        'classes': Turma.count(),
        'responded': CourseApplication.count()
    }

    return render_template('status.html', data=data)


@bp.route('/list_runs')
@login_required(roles='admin', api_route=False)
def list_runs():
    state = peek()
    info = {
        CLEAN: 'Não iniciado.',
        RUNNING: 'Em execução.',
        SUCCESS: 'Concluído com sucesso.',
        FAILURE: 'Concluído com erro.',
        ZOMBIE: 'Interrompido com erro.'
    }

    progress = get_progress()
    print(state)
    print(progress)

    return render_template('execution.html', state=state, status=info[state], progress=progress)

iturmas/templates/base.html
<!DOCTYPE html>
<html lang="pt">

    <head>
        {% block head %}
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <meta name="description" content="">
            <meta name="author" content="">

            <title>{% block title %}{% endblock %} - iTurmas</title>

            <!-- Jquery UI (for autocomplete widget -->
            <link href="{{ url_for('static', filename='css/jquery-ui.min.css') }}" rel="stylesheet">
            <!-- <link href="{{ url_for('static', filename='vendor/bootstrap/css/jquery-ui.structure.min.css') }}" rel="stylesheet">
            <link href="{{ url_for('static', filename='css/jquery-ui.theme.min.css') }}" rel="stylesheet"> -->

            <!-- Bootstrap core CSS -->
            <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
            <link href="{{ url_for('static', filename='css/btn-toggle.css') }}" rel="stylesheet">

            <!-- Google Material Icons -->
            <!-- <<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->

            <!-- Noty -->
            <link href="{{ url_for('static', filename='css/noty.css') }}" rel="stylesheet">

            <!-- Custom styles for this template -->
            <link href="{{ url_for('static', filename='css/iturmas.css') }}" rel="stylesheet">

            <!-- favicon -->
            <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}">

            <style>
                @font-face {
                    font-family: 'Material Icons';
                    font-style: normal;
                    font-weight: 400;
                    src: url({{ url_for('static', filename='fonts/material.woff2') }}) format('woff2'),
                        url({{ url_for('static', filename='fonts/material001.ttf') }}) format('truetype');
                }

                .material-icons {
                    font-family: 'Material Icons';
                    font-weight: normal;
                    font-style: normal;
                    font-size: 24px;
                    line-height: 1;
                    letter-spacing: normal;
                    text-transform: none;
                    display: inline-block;
                    white-space: nowrap;
                    word-wrap: normal;
                    direction: ltr;
                    -webkit-font-feature-settings: 'liga';
                    -webkit-font-smoothing: antialiased;
                }
            {% block styles %}
            {% endblock %}
            </style>
        {% endblock %}
    </head>

    <body>
        {% block body %}
        {% block navbar %}
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                {% block brand_link %}
                <a id="iturmas_brand" class="navbar-brand brand" href="{{ url_for('pages.app_help') }}"><i>iTurmas</i></a>
                {% endblock %}
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    {% block links %}
                    <ul class="navbar-nav ml-auto">
                        {% block link_panel %}
                        <li class="nav-item">
                            <a class="nav-link" href="/panel">Painel</a>
                        </li>
                        {% endblock %}
                        {% block link_students %}
                        <li class="nav-item">
                            <a class="nav-link" href="/students/index">Alunos</a>
                        </li>
                        {% endblock %}
                        {% block link_courses %}
                        <li class="nav-item">
                            <a class="nav-link" href="/courses/index">Disciplinas</a>
                        </li>
                        {% endblock %}
                        {% block link_classes %}
                        <li class="nav-item">
                            <a class="nav-link" href="/classes/index">Turmas</a>
                        </li>
                        {% endblock %}
                        {% block link_logout %}
                        <li class="nav-item">
                            <a class="nav-link" href="/logout"><i class="material-icons">exit_to_app</i></a>
                        </li>
                        {% endblock %}
                    </ul>
                    {% endblock %} {# LINKS #}
                </div>
            </div>
        </nav>
        {% endblock %} {# NAVBAR #}

        {% block modals %}

        <!-- Spinner Modal -->
        <div class="modal fade" id="spinnerModal" tabindex="-1" role="dialog" aria-labelledby="spinnerModalLabel"
             data-backdrop="static" data-keyboard="false" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Processando...</h5>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button> -->
              </div>
              <div class="modal-body" style="text-align: center;">
                <div class="my-loader" style="display: inline-block;"></div>
              </div>
              <!-- <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div> -->
            </div>
          </div>
        </div>
        {% endblock %} {# MODALS #}



        <!-- Page Content -->
        <div class="container" style="min-height: 100vh;">
        {% block content %}
            <div class="row">
                <!-- Blog Entries Column -->
                <div class="col-md-8" id="entries">
                    {% block entries %}
                    <!-- Blog Post
                    <div class="card my-4">
                        <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
                        <div class="card-body">
                            <h2 class="card-title">Post Title</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
                            <a href="#" class="btn btn-primary">Read More &rarr;</a>
                        </div>
                        <div class="card-footer text-muted">
                            Posted on January 1, 2017 by
                            <a href="#">Start Bootstrap</a>
                        </div>
                    </div> -->
                    {% endblock %} {# ENTRIES #}
                </div>


                <!-- Sidebar Widgets Column -->
                <div class="col-md-4">
                    {% block sidebar %}
                    <!-- Search Widget
                    <div class="card my-4">
                        <h5 class="card-header">Buscar</h5>
                        <div class="card-body">
                            <div class="input-group">
                                <input id="search_string" type="text" class="form-control" placeholder="nome ou RA">
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary" type="button"
                                            style="padding: .2em; text-align: center; vertical-align: middle;" id="search_button"
                                            onclick="search(0);">
                                        <i class="material-icons" style="font-size: 24px;">search</i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div> -->
                    {% endblock %} {# SIDEBAR #}
                </div>


            </div> <!-- /.row -->

        {% endblock %} {# CONTENT #}
        </div> <!-- /.container -->

        <!-- Footer -->
        {% block footer %}
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; iTurmas 2019</p>
                <p class="m-0 text-center text-white">
                    {% if 'email' in session %}
                    {% if session.session_object is defined %}
                    {% if session.session_object.role == 'admin' %}Usuário logado como <i>admin</i>{% else %}Usuário logado com o email
                    {{ session.email }} e permissões de aluno{% endif %}.
                    {% endif %}
{#                    {% else %}
                        Ninguem está logado. #}
                    {% endif %}
                </p>
            </div> <!-- /.container -->
        </footer>
        {% endblock %} {# FOOTER #}


        {% block scripts %}
        <!-- Bootstrap core JavaScript -->
        <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/jquery-ui.min.js') }}"></script>
        <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

        <!-- Noty -->
        <script src="{{ url_for('static', filename='js/noty.min.js') }}"></script>

        <!-- Bootbox -->
        <script src="{{ url_for('static', filename='js/bootbox.all.min.js') }}"></script>

        <script src="{{ url_for('static', filename='js/notify.js') }}"></script>
        {% endblock %} {# SCRIPTS #}
        {% endblock %} {# BODY #}
        <script>
            var msgs = []

            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        msgs.push("{{ message }}");
                    {% endfor %}
                {% endif %}
            {% endwith %}

            msgs.reverse()
            console.log(msgs)

            const showMessages = (remaining) => {
                if (!remaining.length)
                    return;
                const msg = remaining.pop()
                flash(msg)
                setTimeout(() => {
                    showMessages(remaining)
                }, 2000)
            }

            showMessages(msgs);
        </script>
    </body>
</html>

iturmas/templates/class_pref_range.html
{% for record in records %}
    <div class="card mb-4">
        <div class="card-header" data-toggle="collapse"
             data-target="#collapse{{ record.code }}">
            <span class="card-title">
                {% set p = parse_json(record.properties) %}
                {{ record.code }} - prof. {{ p.PROFESSOR | d('não informado') }}
                {% if 'CARGA' in p %}- carga horária {{ p.CARGA }}h
                {% endif %}- {{ record.schedule }}
{#                {{ record.class_code }} - {{ record.properties | properties2show('classes') }} -
                {{ record.schedule }} #}
            </span>
            <i class="material-icons btn-link no-underline" style="float: right; cursor: pointer;"
               onclick="event.stopPropagation(); add_item('{{ record.code }}', '{{ record.course_code }} - {{ record.properties | properties2show('classes') }} - {{ record.schedule }}');">add_box</i>
        </div>
        <div class="collapse"  id="collapse{{ record.code }}" data-iturmas-name="{{ record['courses.name'] }}">
            <div class="card-body">
                <p class="card-text">
                    HORÁRIO: {{ record.schedule }}<br>
                    <!-- CÓDIGO: {{ record.code }}<br> -->
                    CÓDIGO DISC.: {{ record.course_code }}<br>
                    {% set p = parse_json(record.properties) %}
                    {% for key in p %}
                        {{ key | upper }}: {{ p[key] }}<br>
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
{% endfor %}

iturmas/templates/classes.html
{% extends "base.html" %}

{% block title %}Turmas{% endblock %}

{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/dropzone.css') }}" rel="stylesheet">
{% endblock %}

{% block link_classes %}
    <li class="nav-item active">
        <a class="nav-link" href="#">Turmas
            <span class="sr-only">(current)</span>
        </a>
    </li>
{% endblock %}

{% block modals %}
    {{ super() }}
    <!-- Modal -->
    <div class="modal fade" id="editClassModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="editClassModalLabel">Editar turma</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <form id="formEditClass">
                        <div class="form-group">
                            <!-- <label for="exampleInputPassword1">Password</label> -->
                            <div style="display: inline-block; position: relative; width: 100%;">
                                <input type="text" class="form-control" id="classCodeEditInput"
                                   placeholder="Código da turma" disabled>
                                <div style="position: absolute; left:0; right:0; top:0; bottom:0;"
                                   onclick="showWarning();"></div>
                            </div>​
                            <p class="my-warning my-hidden" id="editCodeWarning" style="line-height: 0.9;" >
                                <small>
                                    Impossível alterar o código da turma via este formulário.<br>
                                    Exclua a turma e insira-a novamente com o código desejado.
                                </small>
                            </p>
                        </div>
                        <div class="form-group">
                            <!-- <label for="studentInputName">Nome completo</label> -->
                            <input type="text" class="form-control" id="classCourseCodeEditInput"
                                   placeholder="Código da disciplina">
                        </div>
                        <div class="form-group">
                            <!-- <label for="exampleInputPassword1">Password</label> -->
                            <input type="text" class="form-control" id="classScheduleEditInput"
                                   placeholder="Horários das aulas">
                        </div>
                        <div class="form-group">
                            <!-- <label for="exampleInputPassword1">Password</label> -->
                            <input type="text" class="form-control" id="classVacanciesEditInput"
                                   placeholder="Número de vagas">
                        </div>
                        <div class="form-group">
                            <label for="classPropertiesEditInput">Propriedades</label>
                            <textarea class="form-control" id="classPropertiesEditInput"
                                       placeholder="properties.keys()" rows="5"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="cancel_edit_class();">
                        Cancelar
                    </button>
                    <button type="button" class="btn btn-primary" onclick="finish_edit_class();" >
                        Save changes
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block sidebar %}
    <!-- Search Widget SEARCH STUDENTS -->
    <div class="card my-4">
        <h5 class="card-header">Buscar</h5>
        <div class="card-body">
            <div class="input-group">
                <input id="search_string" type="text" class="form-control" placeholder="Código, nome ou professor">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="button"
                            style="padding: .2em; text-align: center; vertical-align: middle;" id="search_button"
                            onclick="search_string = $('#search_string').val(); search(0);">
                        <i class="material-icons" style="font-size: 24px;">search</i>
                    </button>
                </span>
            </div>

            <div class="input-group mb-3" style="margin-top: 1em;">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="maxperpageSelect">Por página, mostrar</label>
                </div>
                <select class="custom-select" id="maxperpageSelect"
                    onChange="javascript:max_per_page = document.getElementById('maxperpageSelect').value; search();">
                    <option value="5">5 entradas</option>
                    <option selected value="10">10 entradas</option>
                    <option value="20">20 entradas</option>
                    <option value="50">50 entradas</option>
                </select>
            </div>
        </div>
    </div>

    <!-- Side Widget INSERT STUDENT -->
    <div class="card my-4">
        <h5 id="insertCardheader" class="card-header">Inserir</h5>
        <div class="card-body">
            <!-- <p>Para inserir um aluno manualmente, coloque os dados do aluno nos campos abaixo e clique em "Inserir".</p> -->
            <form>
                <div class="form-group">
                    <!-- <label for="studentInputName">Nome completo</label> -->
                    <input type="text" class="form-control" id="classCodeInsertInput"
                           placeholder="Código da turma">
                </div>
                <div class="form-group">
                    <!-- <label for="exampleInputPassword1">Password</label> -->
                    <input type="text" class="form-control" id="classCourseCodeInsertInput"
                           placeholder="Código da disciplina">
                </div>
                <div class="form-group">
                    <!-- <label for="exampleInputPassword1">Password</label> -->
                    <input type="text" class="form-control" id="classScheduleInsertInput"
                           placeholder="Horários das aulas">
                </div>
                <div class="form-group">
                    <!-- <label for="exampleInputPassword1">Password</label> -->
                    <input type="text" class="form-control" id="classVacanciesInsertInput"
                           placeholder="Número de vagas">
                </div>
                <div class="form-group">
                    <label for="classPropertiesInsertInput">Propriedades</label>
                    <textarea class="form-control" id="classPropertiesInsertInput"
                               placeholder="em formato JSON" rows="5"></textarea>
                </div>
                <button id="btnInsert" type="button" class="btn btn-primary" onclick="insert_class();">Inserir</button>
            </form>
        </div>
    </div>

    <!-- Side Widget UPLOAD CSV
    <div class="card my-4" style="margin-bottom: 10em;">
        <h5 class="card-header"><i>Upload</i> CSV</h5>
        <div class="card-body">

                <div id="myDropzone" class="dropzone">
                    <div class="fallback">
                        <input name="file" type="file" multiple/>
                    </div>
                </div>

            <h5 id="uploadInfoHeader" class="collapsed" data-toggle="collapse" data-target="#uploadInfo">
                Formato do arquivo
                <i class="material-icons" style="float: right;">expand_less</i>
            </h5>
            <div class="collapse" id="uploadInfo">
                <div>
                    <p style="margin-top: 1em;">O arquivo CSV com os registros das turmas deve ser codificado em
                        <i>utf-8</i>, usar <i>ponto-e-vírgula</i> como delimitador de campos, <i>aspas simples</i>
                        como delimitador de texto (em todos os campos de texto), e conter a linha de cabeçalho.
                    </p>
                    <p>
                        As quatro primeiras colunas serão interpretadas como: código da turma, código da disciplina,
                        horários das aulas e número de vagas, independentemente dos textos correspondentes na linha
                        de cabeçalho.
                    </p>
                    <p> Se houver uma quinta coluna e seu cabeçalho for "propriedades", ela deverá ser a última coluna
                        e as entradas dessa coluna serão interpretadas nos mesmos moldes do campo <i>propriedades</i>
                        acima, i.e. deve ser uma string que codifica um objeto <i>JSON</i>.
                    </p>
                    <p>
                        Opcionalmente, em vez de uma única coluna "propriedades", o CSV pode conter multiplas colunas,
                        cada uma delas discriminando uma propriedade da turma.
                    </p>
                </div>
            </div>
        </div>
    </div> -->
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/pagination.js') }}"></script>
    <script src="{{ url_for('static', filename='js/crud.js') }}"></script>
    <script src="{{ url_for('static', filename='js/search.js') }}"></script>
    <script src="{{ url_for('static', filename='js/domains/class.js') }}"></script>

    <script>
        search(0);
    </script>

    <script>
        var min_len = 3;

        $( "#classCourseCodeInsertInput" ).autocomplete({
          source: "/search/autocomplete/courses",
          minLength: min_len,
          select: function( event, ui ) {
            $('#classCourseCodeInsertInput').val(ui.item.value);
          }
        });

        $( "#classCourseCodeEditInput" ).autocomplete({
          source: "/search/autocomplete/courses",
          minLength: min_len,
          appendTo: '#formEditClass',
          select: function( event, ui ) {
            $('#classCourseCodeEditInput').val(ui.item.value);
          }
        });
    </script>
{% endblock %}

iturmas/templates/course_pref_range.html
{% for course in records %}
    <div class="card mb-4">
        <div class="card-header" data-toggle="collapse"
             data-target="#collapse{{ course.code }}">
            <span class="card-title">{{ course.name }}</span>
            <i class="material-icons btn-link no-underline" style="float: right; cursor: pointer;"
               onclick="event.stopPropagation(); add_item('{{ course.code }}', '{{ course.name }}');">add_box</i>
        </div>
        <div class="collapse"  id="collapse{{ course.code }}" data-iturmas-name="{{ course.name }}">
            <div class="card-body">
                    <p class="card-text">
                        CÓDIGO: {{ course.code }}<br>
                        {% set p = parse_json(course.properties) %}
                        {% for key in p %}
                            {# {{ course.properties | print_dict }} #}
                            {{ key | upper }}: {{ p[key] }}<br>
                        {% endfor %}
                    </p>
            </div>
        </div>
        <!-- <div class="card-footer text-muted">
            Posted on January 1, 2017 by
            <a href="#">Start Bootstrap</a>
        </div> -->
    </div>
{% endfor %}

iturmas/templates/help.html
{% extends "base.html" %}

{% block title %}Senha{% endblock %}

{% block links %}{% endblock %}

{% block brand_link %}
<a id="iturmas_brand" class="navbar-brand brand" href="{{ url_for('pages.index') }}"><i>iTurmas</i></a>
{% endblock %}

{% block head %}
    {{ super() }}
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <style>
        .card-body {
            font-family: 'Raleway', sans-serif;
            font-size: 22px;
        }
    </style>
{% endblock %}

{% block content %}
<!-- <div class="row"> -->
    <div class="card my-4">
         <div class="card-body">
            {{ html_content | safe }}
         </div>
    </div>
<!-- </div> -->
{% endblock %}

iturmas/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block links %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col">&nbsp;</div>

    <div class="card my-4">
        <h5 class="card-header">Login</h5>
        <div class="card-body">
            <form method="POST" action="/auth/login">
            <div class="form-group">
                <div class="input-group">
                    <input name="email" type="text" class="form-control" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input name="password" type="password" class="form-control" placeholder="Password">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input type="hidden" value="{{ request.args.get('next', '') }}" name="next"/>
                    <button class="btn btn-primary" type="submit">Entrar</button>
                </div>
            </div>
            </form>
        </div>
        <div class="card-footer text-muted">
            <a href="{{ url_for('pages.define_new_password') }}">Esqueceu a senha?</a>
        </div>
    </div>

    <div class="col">&nbsp;</div>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/auth/login.js') }}"></script>
{% endblock %}